<?php
/**
 * ChargeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Com\Alacriti\Checkout\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orbipay-Checkout APIs
 *
 * API specification to use the Orbipay-Checkout APIs. This documentation covers the Merchant Account Management and Charge Management related APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: checkout.orbipay@alacriti.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Com\Alacriti\Checkout\Client;

/**
 * ChargeTest Class Doc Comment
 *
 * @category    Class */
// * @description Charge
/**
 * @package     Com\Alacriti\Checkout\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChargeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Charge"
     */
    public function testCharge()
    {
    }

    /**
     * Test attribute "charge_id"
     */
    public function testPropertyChargeId()
    {
    }

    /**
     * Test attribute "confirmation_number"
     */
    public function testPropertyConfirmationNumber()
    {
    }

    /**
     * Test attribute "charge_status"
     */
    public function testPropertyChargeStatus()
    {
    }

    /**
     * Test attribute "charge_amount"
     */
    public function testPropertyChargeAmount()
    {
    }

    /**
     * Test attribute "charge_amount_currency"
     */
    public function testPropertyChargeAmountCurrency()
    {
    }

    /**
     * Test attribute "charge_date"
     */
    public function testPropertyChargeDate()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "funding_account_info"
     */
    public function testPropertyFundingAccountInfo()
    {
    }

    /**
     * Test attribute "customer_info"
     */
    public function testPropertyCustomerInfo()
    {
    }

    /**
     * Test attribute "customer_account_info"
     */
    public function testPropertyCustomerAccountInfo()
    {
    }
}
