<?php
/**
 * ChargeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Com\Alacriti\Checkout\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orbipay-Checkout APIs
 *
 * API specification to use the Orbipay-Checkout APIs. This documentation covers the Merchant Account Management and Charge Management related APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: checkout.orbipay@alacriti.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Com\Alacriti\Checkout\Client;

use \Com\Alacriti\Checkout\Client\Configuration;
use \Com\Alacriti\Checkout\Client\ApiClient;
use \Com\Alacriti\Checkout\Client\ApiException;
use \Com\Alacriti\Checkout\Client\ObjectSerializer;

/**
 * ChargeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Com\Alacriti\Checkout\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChargeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for confirmCharge
     *
     * Confirm Charge.
     *
     */
    public function testConfirmCharge()
    {
    }

    /**
     * Test case for validateCharge
     *
     * Validate Charge.
     *
     */
    public function testValidateCharge()
    {
    }
}
